### ISSUE TITLE
Unsure if still working

### ISSUE THREAD

**Issue by williamweaver** [stvedt/Flickr-Automated-Unfollow#9]
Dear Steve,

Hope all is well.

Thanks for an awesome script.

Not sure if this is still working correctly. The pages will refresh and still none of the non-reciprocal contacts are unfollowed. Any help would be much appreciated.

Thank you and all the best,

William

**Comment by imahawki** [comment]
I'm having the same issue.... the script just pages through contacts but does not unfollow anyone.

**Comment by imahawki** [comment]
Any word on this?

**Comment by virtuadesign** [comment]
Same problem here. The script was doing a very good job since one of the latest update, but it doesn't seem to work anymore.

**Comment by stvedt** [comment]
I will be investigating this issue this weekend. I'll update this with any progress and hopefully a resolution. Thanks for communicating the problem as I don't frequently use this at the moment!

Sent from my iPhone

On Oct 13, 2016, at 20:41, Fran?ois R. Caron <notifications@github.com<mailto:notifications@github.com>> wrote:


Same problem here. The script was doing a very good job since one of the latest update, but it doesn't seem to work anymore.

-

**Comment by stvedt** [comment]
Hey Everyone,

I believe I have tracked down the source of this issue. I have pull requested the change into master: #11. Master should be updated with the latest and working. Let me know if anyone is still having issues.

Best,
Stephen

**Comment by koperman** [comment]
Hello Stvedt,

Until 3 weeks ago the scripts worked very well, but now when running the 2 scripts (more than 2 months & unfollow) they don’t unfollow any contact.
Do you meet same problem ?
Thanks in advance for your answer. 
Best Regards. Peter.
